In [1]:
import numpy as np

In [27]:
#-----------------DEEP COPY-----------------#(PYTHON LISTS)

list_old = [1, 2, 3, 4, 5]
print(list_old)
list_new = list_old[0:3]  # Creates a brand new list [1, 2, 3]
print(list_new)

print("\n")
list_new[0] = 99
print(list_old)  # Output: [1, 2, 3, 4, 5] (ORIGINAL IS SAFE)
print(list_new)



# here slicing of list created a new list in memory using extra storage for the sliced list ..
# MODIFICATIONS made in sliced list will only affect the sliced list not the original list from which it was sliced 
# THIS CONCEPT is called shallow copy where new objects are created after slicing and original objects remains same 




[1, 2, 3, 4, 5]
[1, 2, 3]


[1, 2, 3, 4, 5]
[99, 2, 3]


In [36]:
#--------------------SHALLOW COPY--------------------# (NUMPY ARRAYS)

arr_old = np.arange(1,6)
print(arr_old)

arr_sliced = arr_old[:3]
print("\n")
print(arr_sliced)

# modifiying sliced array
arr_sliced[2] = 7
print(arr_sliced)

print("\n")
print(arr_old)

# OBSERVE , HERE modifications in sliced array were also applied to original array as numpy doesnt create a new array 
# after slicing , sliced array points to the original array in RAM

# NUMPY was desgined for massive datasets , if it made a new copy of array every time we sliced an array , 
# RAM would fill up instantly and may crash the computer as array may be thousands of elements.



[1 2 3 4 5]


[1 2 3]
[1 2 7]


[1 2 7 4 5]


In [ ]:
#------------------ TO USE DEEP COPY IN NUMPY ARRAYS-------------------------#

arr_old = np.array([1, 2, 3, 4, 5])
arr_new = arr_old[0:3].copy() 
# This creates a totally separate object compared to standard slciing where it creates a "VIEW" i.e new array
# points to original one and doesnt have its own copy 

# When we want to make changes in modified(sliced) array without touching original one in numpy , 
# we must use arr_old[:].copy() which creates a new copy (object) for sliced array 

arr_new[0] = 99
print(arr_old) # Output: [1, 2, 3, 4, 5] (STAYED THE SAME)


In [ ]:
#----------------------------VIEW VS OBJECT--------------------#\

# In Python, a slice creates a Copy. 
# In NumPy, a slice creates a View of the sliced array part from the original one ,
# i.e when we are looking at sliced array it is still te original array , 
# but only the sliced part is shown from  the original array , not a new object similar to python lists 
