In [1]:
import numpy as np

In [8]:

arr1 = np.arange(1,5)
arr2 = np.arange(5,9)

print(arr1)
print(arr2)

[1 2 3 4]
[5 6 7 8]


In [15]:
#------------STACKING ARRAY---------------#

# Note we CAN NOT stack 2D ARRAYS we need 1D ARRAYS (VECTORS) to stack

print(np.vstack((arr1,arr2))) # VERTICAL STACK 
print("\n")

print(np.hstack((arr1,arr2))) # HORIZONTAL STACK 
print("\n")

print(np.column_stack((arr1,arr2))) # COLUMN STACK

[[1 2 3 4]
 [5 6 7 8]]


[1 2 3 4 5 6 7 8]


[[1 5]
 [2 6]
 [3 7]
 [4 8]]


In [28]:
#_--------------SPLITTING ARRAY-----------------#

arr = np.arange(16).reshape(4,4)
print(arr)
print("\n")

print(np.hsplit(arr,4))

print("\n")
print(np.vsplit(arr,4))

print("\n")
print(np.vsplit(arr,2))

# NOTE: SPLITTED ARRAYS ARE ALSO 2D ARRAYS EVEN WHEN WE BREAK IT IN 4 PARTS 

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


[array([[ 0],
       [ 4],
       [ 8],
       [12]]), array([[ 1],
       [ 5],
       [ 9],
       [13]]), array([[ 2],
       [ 6],
       [10],
       [14]]), array([[ 3],
       [ 7],
       [11],
       [15]])]


[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]]), array([[12, 13, 14, 15]])]


[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])]
