In [1]:
import numpy as np

In [19]:
#-----------------ARRAY INDEXING-------------#

# Array indexing starts from 0 similar to python lists 
arr = np.arange(10,21)
print(f"{arr}\n")

print(arr[0] , arr[1] , arr[2] ,arr[8], arr[9] , arr[10] )


[10 11 12 13 14 15 16 17 18 19 20]

10 11 12 18 19 20


In [24]:
#---------------ARRAY SLICNG---------------------#

arr = np.arange(10,21)
print(f"{arr}\n")

# to slice from 11 to 15 i.e index 1 to 5 \
# we need to slice array from (START )TO (END INDEX + 1)

arr1 = arr[1:6] 
print(f"{arr1}\n")

arr1 = arr[5:] # assumes till end arr[x:] from index to end slicing 
print(f"{arr1}\n")

arr1 = arr[:5] # till 5 so from 0 to 4th index total 5 elements 
print(f"{arr1}\n")

arr1 = arr[:]
print(f"{arr1}\n") # from start to end 


[10 11 12 13 14 15 16 17 18 19 20]

[11 12 13 14 15]

[15 16 17 18 19 20]

[10 11 12 13 14]

[10 11 12 13 14 15 16 17 18 19 20]



In [27]:
#--------------SLICING WITH STEPS---------#

# to slice with steps
arr1 = arr[::2]
print(f"{arr1}\n")

arr1 = arr[1:9:2]
print(f"{arr1}\n") 

[10 12 14 16 18 20]

[11 13 15 17]

