In [1]:
import numpy as np

In [14]:
#-----------------------2D ARRAY INDEXING--------------#

arr = np.arange(1,31)
arr = arr.reshape(6,5)
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


In [11]:
# -----ROWS-------#
print(arr[0])
print(arr[1])
print(arr[2])
print(arr[3])
print(arr[4])
print(arr[5])

[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]
[16 17 18 19 20]
[21 22 23 24 25]
[26 27 28 29 30]


In [15]:
#--------ELEMENTS------#
print(arr[5][4])

30


In [22]:
# ---------------------2D ARRAY SLICING---------------------#


print(arr)

# we want 2,3,7,8 square to be sliced out

print(arr[0:2,1:3]) # 0,1 two rows to slice so 0 to 2 slicing for rows and 1,2 two columns to slice so 1 to 3 column slicing

# we want 19-30 matrix sliced out (3*2)
print("\n")
print(arr[3:6,3:5])

print("\n")
# to go to end by default leave end index empty 
print(arr[3:,3:])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]
[[2 3]
 [7 8]]


[[19 20]
 [24 25]
 [29 30]]


[[19 20]
 [24 25]
 [29 30]]


In [27]:
# ------------TO SELECT COLUMNS AND ROWS------------#

print(arr)

print("\n")
print(arr[0,:])

print("\n")
print(arr[:,2:4])

print("\n")
print(arr[:,4])



[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


[1 2 3 4 5]


[[ 3  4]
 [ 8  9]
 [13 14]
 [18 19]
 [23 24]
 [28 29]]


[ 5 10 15 20 25 30]
